name: Grant Ships Envio
contracts:
  - name: Registry
    handler: src/Registry.ts
    abi_file_path: abis/Registry.json
    events:
    - event: ProfileCreated(bytes32 indexed profileId, uint256 nonce, string name, (uint256,string) metadata, address owner, address anchor)
    - event: ProfileMetadataUpdated(bytes32 indexed profileId, (uint256,string) metadata)
      isAsync: true
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
  - name: GameManagerFactory
    handler: src/GameManagerFactory.ts
    events:
    - event: FactoryInitialized(address rootAccount)
    - event: GameManagerDeployedWithPool(address gameManagerAddress, bytes32 profileId, uint256 poolId, string templateName, address tokenAddress, bytes initData, (uint256,string) poolMetadata, (uint256,string) profileMetadata)
    - event: RootAccountSwitched(address newRootAccount)
    - event: TemplateCreated(string name, address templateAddress)
  - name: GameManagerStrategy
    handler: src/GameManagerStrategy.ts
    events:
    - event: Registered(address anchorAddress, bytes applicationData, address sender)
    - event: GameManagerInitialized(uint256 gameFacilitatorId,address hatsAddress,address rootAccount,address token,uint256 poolId)
    - event: RoundCreated(uint256 gameIndex,uint256 totalRoundAmount)
    - event: ShipLaunched(address shipAddress,uint256 shipPoolId,address recipientId,string shipName,(uint256,string) metadata)
    - event: RecipientRejected(address recipientAddress,(uint256,string) reason)
    - event: RecipientAccepted(address recipientAddress,(uint256,string) reason)
    - event: GameActive(bool active,uint256 gameIndex)
    - event: UpdatePosted(string tag,uint256 role,address recipientId,(uint256,string) content)
    - event: Allocated(address recipientId, uint256 amount,address tokenAddress, address sender)
    - event: Distributed(address recipientId, address shipAddress, uint256 grantAmount, address sender)
    - event: GameRoundTimesCreated(uint256 gameRoundIndex,uint256 startTime,uint256 endTime)
  - name: GrantShipFactory
    handler: src/GrantShipFactory.ts
    events: 
    # Voting
  - name: HatsPoster
    handler: src/HatsPoster.ts
    events:
    - event: Initialized(address hatsAddress, uint256[] hatIds)
    - event: PostRecord(string tag, bytes32 nonce, uint256 hatId, (uint256, string))
    - event: PostEvent(string tag, uint256 hatId, (uint256, string))
  - name: FastFactory
    handler: src/FactoryHandlers.ts
    events:
    - event: FactoryInitialized(address admin)
    - event: AdminAdded(address admin)
    - event: AdminRemoved(address admin)
    - event: ContestTemplateCreated(string contestVersion, address contestAddress, (uint256,string) contestInfo)
    - event: ContestTemplateDeleted(string contestVersion, address contestAddress)
    - event: ModuleTemplateCreated(string moduleName, address moduleAddress, (uint256,string) moduleInfo)
    - event: ModuleTemplateDeleted(string moduleName, address moduleAddress)
    - event: ModuleCloned(address moduleAddress, string moduleName, string filterTag)
    - event: ContestCloned(address contestAddress, string contestVersion, string filterTag)
    - event: ContestBuilt(string votesModule, string pointsModule, string choicesModule, string executionModule, address contestAddress, string contestVersion, string filterTag)
  - name: HatsAllowList
    handler: src/HatsAllowList.ts
    events: 
    - event: Initialized(address contest, address hatsAddress, uint256 hatId)
    - event: Registered(bytes32 choiceId, ((uint256, string), bytes, bool), address contest)
    - event: Removed(bytes32 choiceId, address contest)
      isAsync: true
  - name: ERC20VotesPoints
    handler: src/ERC20VotesPoints.ts
    events:
    - event: Initialized(address contest, address token, uint256 votingCheckpoint)
  - name: SBTBalancePoints  
    handler: src/SBTBalancePoints.ts
    events:
    - event: Initialized(address contest, address token)
  - name: TimedVotes
    handler: src/TimedVotes.ts
    events:
    - event: Initialized(address contest, uint256 duration)
    - event: VotingStarted(uint256 startTime, uint256 endTime)
      isAsync: true
    - event: VoteCast(address indexed voter, bytes32 choiceId, uint256 amount, (uint256, string))
      isAsync: true
    - event: VoteRetracted(address indexed voter, bytes32 choiceId, uint256 amount, (uint256, string))
      isAsync: true
  - name: Contest_v0_1_0
    handler: src/Contest.ts
    events:
    - event: ContestInitialized(address votesModule, address pointsModule, address choicesModule, address executionModule, bool isContinuous, bool isRetractable, uint8 status)
      isAsync: true
    - event: ContestStatusChanged(uint8 status)
networks:
- id: 421614 # Arbitrum Sepolia
  start_block: 39353224
  end_block: null
  contracts:
  - name: Registry
    abi_file_path: abis/Registry.json
    address: 
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GameManagerFactory
    address: 
    - 0x103f8273b0ea01ffd5a457ed51fdaca81e971378
  - name: GameManagerStrategy
    address:   
  - name: FastFactory
    address: 0x2bABC10b90c67399F820433358fEb85fbB24f22f
  - name: HatsAllowList
    address: 
  - name: ERC20VotesPoints
    address:
  - name: SBTBalancePoints
    address:  
  - name: TimedVotes
    address:
  - name: Contest_v0_1_0
    address:  
  - name: HatsPoster
    address: 0x4F0dc1C7d91d914d921F3C9C188F4454AE260317
- id: 42161 # Arbitrum One
  start_block: 195499276
  end_block: null
  contracts:
  - name: Registry
    address: 
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GameManagerFactory
    address:
    - 0x012Ab5AC3adff0958cEc0317b8307D14A39a62A6
  - name: GameManagerStrategy
    address:
  - name: FastFactory
    address: 0x98917Fe3554acFB9f982F6A4fE5Ad377EE55ee70
  - name: HatsAllowList
    address: 
  - name: ERC20VotesPoints
    address:
  - name: SBTBalancePoints
    address:  
  - name: TimedVotes
    address:
  - name: Contest_v0_1_0
    address:  
  - name: HatsPoster
    address: 0x363a6eFF03cdAbD5Cf4921d9A85eAf7dFd2A7efD

  
